### ISSUE TITLE
Cannot set existing StorageClass with `existingStorageClassName`.

### ISSUE THREAD

**Issue by jaggerwang** [datastax/pulsar-helm-chart#105]
## Problem

I both tried setting `existingStorageClassName` under global `default_storage` or under specific volume to an existing StorageClass `ebs-pulsar`, but the created PVCs are still using the default StorageClass `ebs-gp3`.

![image](https://user-images.githubusercontent.com/1255011/146861957-00bb4452-b83e-48a1-b620-fcd7c1641b20.png)

![image](https://user-images.githubusercontent.com/1255011/146862008-9381e34c-53d2-4a29-9b7f-eb54c23a4ee5.png)

My custom helm values:
```yaml
components:
  zookeeper: true
  bookkeeper: true
  autorecovery: true
  broker: true
  functions: true
  proxy: true
  toolset: true
  pulsar_manager: true
monitoring:
  prometheus: false
  grafana: false
volumes:
  persistence: true
default_storage:
  existingStorageClassName: ebs-pulsar
antiAffinity:
  host:
    enabled: true
    mode: required
  zone:
    enabled: true
nodeSelector:
  dedicated: infrastructure
zookeeper:
  volumes:
    data:
      name: data
      size: 40Gi
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: infrastructure
bookkeeper:
  volumes:
    journal:
      name: journal
      size: 20Gi
    ledgers:
      name: ledgers
      size: 100Gi
    ranges:
      name: ranges
      size: 10Gi
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: infrastructure
autorecovery:
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: infrastructure
broker:
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: infrastructure
functions:
  volumes:
    data:
      name: logs
      size: 10Gi
      existingStorageClassName: ebs-pulsar
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: infrastructure
proxy:
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: infrastructure
toolset:
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: infrastructure
pulsar_manager:
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: infrastructure

```

## Env

Kubernetes: v1.21 in EKS
Helm: v3.3.4
Pulsar Chart: v2.7.6
