### ISSUE TITLE
Fix org.apache.kafka.common.errors.UnknownServerException on ktool deployment

### ISSUE THREAD

**Issue by MMirelli** [datastax/pulsar-helm-chart#118]
When the deploying the helmchart with values:

```
              enableAntiAffinity: no
              initialize: true  # ASF Helm Chart
              restartOnConfigMapChange:
                enabled: yes
              image:
                zookeeper:
                  repository: pulsar-repo
                  tag: 2.8.x
                bookie:
                  repository: pulsar-repo
                  tag: 2.8.x
                bookkeeper:
                  repository: pulsar-repo
                  tag: 2.8.x
                autorecovery:
                  repository: pulsar-repo
                  tag: 2.8.x
                broker:
                  repository: pulsar-repo
                  tag: 2.8.x
                proxy:
                  repository: pulsar-repo
                  tag: 2.8.x
                functions:
                  repository: pulsar-repo
                  tag: 2.8.x
                function:
                  repository: pulsar-repo
                  tag: 2.8.x
              extra:
                function: yes
                burnell: no
                burnellLogCollector: no
                pulsarHeartbeat: no
                pulsarAdminConsole: no
                autoRecovery: no
                functionsAsPods: yes
              default_storage:
                existingStorageClassName: server-storage
              volumes:
                data: #ASF Helm Chart
                  storageClassName: existent-storage-class
              zookeeper:
                replicaCount: 3
              bookkeeper:
                replicaCount: 3
              broker:
                component: broker
                replicaCount: 2
                ledger:
                  defaultEnsembleSize: 2
                  defaultAckQuorum:  2
                  defaultWriteQuorum: 2
                service:
                  annotations: {}
                  type: ClusterIP
                  headless: false
                  ports:
                  - name: http
                    port: 8080
                  - name: pulsar
                    port: 6650
                  - name: https
                    port: 8443
                  - name: pulsarssl
                    port: 6651
                  - name: kafkaplaintext
                    port: 9092
                  - name: kafkassl
                    port: 9093
                  - name: kafkaschemareg
                    port: 8001
                kafkaOnPulsarEnabled: true
                kafkaOnPulsar:
                  saslAllowedMechanisms: PLAIN
                  brokerEntryMetadataInterceptors: "org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor,org.apache.pulsar.common.intercept.AppendBrokerTimestampMetadataInterceptor"
                  kopSchemaRegistryEnable: true
              function:
                replicaCount: 1
                functionReplicaCount: 1
                runtime: "kubernetes"
              proxy:
                replicaCount: 2
                autoPortAssign:
                  enablePlainTextWithTLS: yes
                service:
                  type: ClusterIP
                  autoPortAssign:
                    enabled: yes
                configData:
                  PULSAR_MEM: "\"-Xms400m -Xmx400m -XX:MaxDirectMemorySize=112m\""
                  PULSAR_PREFIX_kafkaListeners: "SASL_PLAINTEXT://0.0.0.0:9092"
                  PULSAR_PREFIX_kafkaAdvertisedListeners: "SASL_PLAINTEXT://pulsar-proxy:9092"
                  PULSAR_PREFIX_saslAllowedMechanisms: PLAIN
                  PULSAR_PREFIX_kafkaProxySuperUserRole: superuser
                  PULSAR_PREFIX_kopSchemaRegistryProxyEnableTls: "false"
                  PULSAR_PREFIX_kopSchemaRegistryEnable: "true"
                  PULSAR_PREFIX_kopSchemaRegistryProxyPort: "8081"
                extensions:
                  enabled: true
                  extensions: "kafka"
                  containerPorts:
                    - name: kafkaplaintext
                      containerPort: 9092
                    - name: kafkassl
                      containerPort: 9093
                    - name: kafkaschemareg
                      containerPort: 8081
                  servicePorts:
                  - name: kafkaplaintext
                    port: 9092
                    protocol: TCP
                    targetPort: kafkaplaintext
                  - name: kafkassl
                    port: 9093
                    protocol: TCP
                    targetPort: kafkassl
                  - name: kafkaschemareg
                    port: 8081
                    protocol: TCP
                    targetPort: kafkaschemareg
              grafanaDashboards:
                enabled: no
              pulsarAdminConsole:
                replicaCount: 0
                service:
                  type: ClusterIP
              grafana: #ASF Helm Chart
                service:
                  type: ClusterIP
              pulsar_manager:
                service: #ASF Helm Chart
                  type: ClusterIP
              kube-prometheus-stack: # Luna Streaming Helm Chart
                enabled: no
                prometheusOperator:
                  enabled: no
                grafana:
                  enabled: no
                  adminPassword: e9JYtk83*4#PM8
                  service:
                    type: ClusterIP
              pulsarSQL:
                service:
                  type: ClusterIP
              enableTls: no
              enableTokenAuth: no
```
The following error is thrown by the `ktool` pod:

```
[2022-01-01 12:49:53,587] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:66)
io.confluent.ksql.util.KsqlServerException: Could not get Kafka cluster configuration!
	at io.confluent.ksql.services.KafkaClusterUtil.getConfig(KafkaClusterUtil.java:96)
	at io.confluent.ksql.security.KsqlAuthorizationValidatorFactory.isKafkaAuthorizerEnabled(KsqlAuthorizationValidatorFactory.java:81)
	at io.confluent.ksql.security.KsqlAuthorizationValidatorFactory.create(KsqlAuthorizationValidatorFactory.java:51)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:724)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:637)
	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:152)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:59)
Caused by: org.apache.kafka.common.errors.UnknownServerException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /10.244.4.18:9092
```

This is resolved by reverting [ab5216de64e5868a378a2a08f0ff6efa0f0430ef](https://github.com/datastax/pulsar-helm-chart/commit/ab5216de64e5868a378a2a08f0ff6efa0f0430ef), as it can be seen by using this ["version" of the helmchart](https://github.com/MMirelli/pulsar-helm-chart/commit/4c1aa9eb254deb76f44208757c739c9db9756a07). However, a better solution is needed.
