### ISSUE TITLE
Add documentation to disable `kube-prometheus-stack` optional features

### ISSUE THREAD

**Issue by MMirelli** [datastax/pulsar-helm-chart#121]
Documentation should be added to cover the issue described below.

Whenever the conditional dependency [`kube-prometheus-stack.enabled`](https://github.com/MMirelli/pulsar-helm-chart/blob/master/helm-chart-sources/pulsar/Chart.yaml#L30) is disabled, it does not produce the expected behaviour of disabling all the Prometheus stack components. In fact, each of those should be disabled in the `values.yaml`, by adding the following:

```
kube-prometheus-stack:
  enabled: false
  prometheusOperator:
    enabled: false
  grafana:
    enabled: false
    adminPassword: e9JYtk83*4#PM8
  alertmanager:
    enabled: false
  prometheus:
    enabled: false
```

It should be noted that unless all the Prometheus components are disabled, the helmchart will attempt to install Prometheus CRDs. This might be an issue in cases when the service account used to deploy the cluster does not have enough permissions to install Custom Resources Definitions.
