### ISSUE TITLE
externalDNS version doesn't work with k8s 1.22

### ISSUE THREAD

**Issue by cdbartholomew** [datastax/pulsar-helm-chart#153]
The version of externalDNS image used by the chart does not work in k8s 1.22.

The following version works: k8s.gcr.io/external-dns/external-dns:v0.10.2

Also, since the older ingress API versions were removed, the ClusterRole rules needs to be updated to this:

```
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["networking","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get","watch","list"]
```
