### ISSUE TITLE
Correct port mappings in proxy ingress

### ISSUE THREAD

**Issue by ddieruf** [datastax/pulsar-helm-chart#219]
Currently, the pulsar proxy ingress exposes port 8001 with tcp at a path of /. While I'm not entirely sure what this port is user for, the service behind the ingress has quite a few other ports open (see below). Should the ingress be more in sync with the service? Maybe 6650 and 8080 be opened in the case of non tls and 6651 and 8443 in the case of tls.

The ports used in the proxy service:
```yaml
  - name: https
    nodePort: 31200
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: pulsarssl
    nodePort: 30087
    port: 6651
    protocol: TCP
    targetPort: 6651
  - name: wss
    nodePort: 30535
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: http
    nodePort: 30284
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: pulsar
    nodePort: 30290
    port: 6650
    protocol: TCP
    targetPort: 6650
  - name: ws
    nodePort: 31025
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: burnell
    nodePort: 30168
    port: 8964
    protocol: TCP
    targetPort: 8964
```
