### ISSUE TITLE
Pulsar heartbeat init container logic

### ISSUE THREAD

**Issue by ddieruf** [datastax/pulsar-helm-chart#221]
The heartbeat deployment has an initContainer that waits for bookkeeper to be ready. The logic to wait is a loop that curls the broker on a certain port. If `enableTls` is `true` then the loop uses the broker statefulset and attempts an https connection on port 8443. What seems odd to me, is the broker statefulset only opens ports 8080 and 6650.

Should the broker statefulset also open an additional https port?

```yaml
    ports:
        {{- if .Values.enableTls }}
        - name: https
          containerPort: 8443
        {{- end }}
        - name: http
          containerPort: 8080
        - name: pulsar
          containerPort: 6650
```

Note: adding this new port opening didn't solve my issue of the heartbeat's initContainer completing successfully but this seems like a needed thing.
