### ISSUE TITLE
Activation state storage KO

### ISSUE THREAD

**Issue by brunoflament** [datastax/pulsar-helm-chart#228]
Hello,

The Bookie service is configured to listen on port 3181. What is port 3181 in bookie? Is it port 4181 instead?

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: pulsar
    meta.helm.sh/release-namespace: pulsar
  labels:
    app: pulsar
    app.kubernetes.io/managed-by: Helm
    chart: pulsar-2.9.3
    cluster: pulsar
    component: bookie
    heritage: Helm
    release: pulsar
  name: pulsar-bookie
  namespace: pulsar
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: bookie
    port: 3181
    protocol: TCP
    targetPort: 3181
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
```

https://pulsar.apache.org/docs/functions-worker#configure-stateful-functions-to-run-with-broker
