### ISSUE TITLE
PulsarSQL coordinator liveness probe unauthorized

### ISSUE THREAD

**Issue by hyperevo** [datastax/pulsar-helm-chart#300]
The PulsarSQL liveness probe fails causing a crashloopbackoff. It fails because because presto requires authentication but the livenessprobe does not use authentication as seen here: https://github.com/datastax/pulsar-helm-chart/blob/a6e2cfb6b76044f1d88678756f5aa41cae671701/helm-chart-sources/pulsar/templates/pulsarSql/deployment-coordinator.yaml#L152 

The presto service doesnt by defualt even require a password. just a username. This problem is fixed by adding the following to the liveness probe in the above link. This adds the base64 encoded username of "admin":
```yaml
          httpHeaders:
            - name: Authorization
              value: Basic YWRtaW46
```

I can make a PR to add this in but I wanted to ask about it here first. Does anyone object to this solution? Another solution could be to set up actual authentication and handle that correctly.
