### ISSUE TITLE
Remove default credentials from values file

### ISSUE THREAD

**Issue by cdbartholomew** [datastax/pulsar-helm-chart#34]
There are default credentials for configuring Tardigrade and Grafana in the values file:
```
tardigrade:
  access: access-key-generated-with-uplink
  accessKey: 2J7EJY4xTK6uHKqnCE4nAhdGfXqy
  secretKey: 4YeYwYdsoFFpvtNFuncWcTVqSTPL
  service:
    port: 7777
    type: ClusterIP
```

And:
```
  grafana:
    enabled: true
    # namespaceOverride: "monitoring"
    testFramework:
      enabled: false
    defaultDashboardsEnabled: true
    adminPassword: ZhF9sS8B7PQSTR
```
 These default values should be removed.
